[package]
name = "base16-builder"
version = "0.1.0"
authors = ["Abu Khan <cmdwannabe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.12"
structopt = "0.3.20"
serde_yaml = "0.8.7"
